name: latest

"on":
  push:
    branches:
      - master
    paths:
      - latest/*
      - .github/workflows/docker.yml
  pull_request:
    branches:
      - master
    paths:
      - latest/*
      - .github/workflows/docker.yml
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            curicows/technic-solder
            ghcr.io/curicows/technic-solder
            gitea.curicows.com/curicows/technic-solder
          labels: |
            org.opencontainers.image.vendor=Curicows

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Hub login
        id: login1
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Gitea login
        id: login2
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: gitea.curicows.com
          username: ${{ secrets.GITEA_USERNAME }}
          password: ${{ secrets.GITEA_TOKEN }}

      - name: Ghcr login
        id: login3
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build amd64
        id: amd64
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          provenance: false
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            curicows/technic-solder:latest
            ghcr.io/curicows/technic-solder:latest
            gitea.curicows.com/curicows/technic-solder:latest
            curicows/technic-solder:0.11.0
            ghcr.io/curicows/technic-solder:0.11.0
            gitea.curicows.com/curicows/technic-solder:0.11.0
